### ISSUE TITLE
Installing Observatorium on OpenShift issues

### ISSUE THREAD

**Issue by dry923** [observatorium/configuration#429]
Adding this as a tracking for issues that were hit while getting Observatorium to work on an OpenShift cluster and not just using Kind.

Based off using configuration/examples/dev files

1) Dex namespace is not created by default so when applying the manifests dex fails.
2) Test configmap is not part of the tests manifests. Needed to apply configuration/tests/manifests/test-ca-tls.yaml
3) Missing Dex configmap. Needed to apply tests/manifests/observatorium-xyz-tls-dex.yaml
4) By default there is no observatorium route create so we cannot access the api endpoint. Created with this 
```
apiVersion: v1
kind: Route
items:
- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    name: observatorium
    namespace: observatorium
  spec:
    host: observatorium-xyz-observatorium.apps.my.obs.stuff.devshift.org
    port:
      targetPort: 8080
    to:
      kind: Service
      name: observatorium-xyz-observatorium-api
      weight: 100
    wildcardPolicy: None
```
5) observatorium-xyz-thanos-query and observatorium-xyz-thanos-query-frontend service accounts do not have privilege to access the anyuuid scc. Needed to add them via: 
```
# oc adm policy add-scc-to-user anyuid -z observatorium-xyz-thanos-query -n observatorium
# oc adm policy add-scc-to-user anyuid -z observatorium-xyz-thanos-query-frontend -n observatorium
```
6) The observatorium api would start before dex in some cases. I would need to manually delete the observatorium-xyz-observatorium-api pod so it would restart and find the tenant.

After this I was able to port forward from dex to get the bearer token with curl via 
```
# oc port-forward -n dex svc/dex 5556
# curl --request POST --url https://127.0.0.1:5556/dex/token --insecure --data grant_type=password --data username=admin@example.com --data password=password --data client_id=test --data client_secret=ZXhhbXBsZS1hcHAtc2VjcmV0 --data scope="openid email" | sed 's/^{.*"id_token":[^"]*"\([^"]*\)".*}/\1/'
```
I was then able to add it as a data source to Grafana.

Much thanks to @ianbillett and @matej-g !!
